version: "3"
services:
  web:
    build: .
    image: django-rest-jwt-registration
    container_name: web
    restart: on-failure
    env_file:
      - ./.env
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/www
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: "postgres:13.2-alpine"
    container_name: db
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
