# Generated by Django 3.1.7 on 2021-04-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_jwt_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='type',
            field=models.CharField(choices=[('rt', 'Registration token'), ('rd', 'Registration Delete Token'), ('pc', 'Password Change Token')], default='rt', max_length=3),
        ),
    ]
