# Generated by Django 3.1.7 on 2021-04-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_jwt_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='type',
            field=models.CharField(choices=[('rt', 'Registration token'), ('rd', 'Registration Delete Token'), ('pc', 'Password Change Token'), ('ec', 'Change Email Token')], default='rt', max_length=3),
        ),
    ]
