# Generated by Django 3.2.1 on 2021-05-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drjr', '0002_auto_20210412_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
